
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Oct 19 00:38:20 MSK 2015
//----------------------------------------------------

package ru.serce.glu.gluc.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FLOAT_LIT = 36;
  public static final int OP_NE = 27;
  public static final int CHAR = 4;
  public static final int ASTERISK = 20;
  public static final int EQUALS = 30;
  public static final int SLASH = 19;
  public static final int PLUSOP = 17;
  public static final int OP_GT = 23;
  public static final int MINUSOP = 18;
  public static final int DOUBLE = 5;
  public static final int LPAREN = 8;
  public static final int OP_AND = 28;
  public static final int INT = 3;
  public static final int RPAREN = 9;
  public static final int SEMICOLON = 11;
  public static final int OP_GE = 25;
  public static final int BANG = 21;
  public static final int COMMA = 10;
  public static final int IF = 13;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 16;
  public static final int TRUE = 31;
  public static final int error = 1;
  public static final int OP_LT = 22;
  public static final int OP_OR = 29;
  public static final int VOID = 12;
  public static final int OP_LE = 24;
  public static final int LBRACE = 6;
  public static final int ELSE = 14;
  public static final int WHILE = 15;
  public static final int RBRACE = 7;
  public static final int OP_EQ = 26;
  public static final int FALSE = 32;
  public static final int STRING_LIT = 35;
  public static final int INT_LIT = 34;
  public static final int IDENTIFIER = 33;
}

